#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MaisLifeModel;

namespace MaisLifeModel	
{
	[System.Serializable()]
	public partial class Bairro : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private decimal _taxa;
		public virtual decimal Taxa
		{
			get
			{
				return this._taxa;
			}
			set
			{
				this._taxa = value;
			}
		}
		
		private IList<Produto_bairro> _produto_bairros = new List<Produto_bairro>();
		public virtual IList<Produto_bairro> Produto_bairros
		{
			get
			{
				return this._produto_bairros;
			}
            set
            {
                this._produto_bairros = value;
            }
		}
		
		private IList<Endereco> _enderecos = new List<Endereco>();
		public virtual IList<Endereco> Enderecos
		{
			get
			{
				return this._enderecos;
			}
            set
			{
				this._enderecos = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Bairro()
		{
		}
		
		protected Bairro(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Nome = info.GetString("Nome");
			this.Taxa = (decimal)info.GetValue("Taxa", typeof(decimal?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Nome", this.Nome, typeof(string));
			info.AddValue("Taxa", this.Taxa, typeof(decimal?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
