#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MaisLifeModel;

namespace MaisLifeModel	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Usuario_externo> Usuario_externos 
		{
			get
			{
				return this.GetAll<Usuario_externo>();
			}
		}
		
		public IQueryable<Usuario> Usuarios 
		{
			get
			{
				return this.GetAll<Usuario>();
			}
		}
		
		public IQueryable<Produto_bairro> Produto_bairros 
		{
			get
			{
				return this.GetAll<Produto_bairro>();
			}
		}
		
		public IQueryable<Produto> Produtos 
		{
			get
			{
				return this.GetAll<Produto>();
			}
		}
		
		public IQueryable<Pedido> Pedidos 
		{
			get
			{
				return this.GetAll<Pedido>();
			}
		}
		
		public IQueryable<Parceiro> Parceiros 
		{
			get
			{
				return this.GetAll<Parceiro>();
			}
		}
		
		public IQueryable<Endereco> Enderecos 
		{
			get
			{
				return this.GetAll<Endereco>();
			}
		}
		
		public IQueryable<Contato> Contatos 
		{
			get
			{
				return this.GetAll<Contato>();
			}
		}
		
		public IQueryable<Carrinho_produto> Carrinho_produtos 
		{
			get
			{
				return this.GetAll<Carrinho_produto>();
			}
		}
		
		public IQueryable<Carrinho> Carrinhos 
		{
			get
			{
				return this.GetAll<Carrinho>();
			}
		}
		
		public IQueryable<Bairro> Bairros 
		{
			get
			{
				return this.GetAll<Bairro>();
			}
		}
		
		public IQueryable<Mapaentrega> Mapaentregas 
		{
			get
			{
				return this.GetAll<Mapaentrega>();
			}
		}
		
		public IQueryable<Mapa_pedido> Mapa_pedidos 
		{
			get
			{
				return this.GetAll<Mapa_pedido>();
			}
		}
		
		public IQueryable<Devolucao_produto> Devolucao_produtos 
		{
			get
			{
				return this.GetAll<Devolucao_produto>();
			}
		}
		
		public IQueryable<Devolucao> Devolucaos 
		{
			get
			{
				return this.GetAll<Devolucao>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Usuario_externo> Usuario_externos
		{
			get;
		}
		IQueryable<Usuario> Usuarios
		{
			get;
		}
		IQueryable<Produto_bairro> Produto_bairros
		{
			get;
		}
		IQueryable<Produto> Produtos
		{
			get;
		}
		IQueryable<Pedido> Pedidos
		{
			get;
		}
		IQueryable<Parceiro> Parceiros
		{
			get;
		}
		IQueryable<Endereco> Enderecos
		{
			get;
		}
		IQueryable<Contato> Contatos
		{
			get;
		}
		IQueryable<Carrinho_produto> Carrinho_produtos
		{
			get;
		}
		IQueryable<Carrinho> Carrinhos
		{
			get;
		}
		IQueryable<Bairro> Bairros
		{
			get;
		}
		IQueryable<Mapaentrega> Mapaentregas
		{
			get;
		}
		IQueryable<Mapa_pedido> Mapa_pedidos
		{
			get;
		}
		IQueryable<Devolucao_produto> Devolucao_produtos
		{
			get;
		}
		IQueryable<Devolucao> Devolucaos
		{
			get;
		}
	}
}
#pragma warning restore 1591
