#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MaisLifeModel;

namespace MaisLifeModel	
{
	[System.Serializable()]
	public partial class Mapaentrega : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _observacao;
		public virtual string Observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				this._observacao = value;
			}
		}
		
		private DateTime? _data_entrega;
		public virtual DateTime? Data_entrega
		{
			get
			{
				return this._data_entrega;
			}
			set
			{
				this._data_entrega = value;
			}
		}
		
		private IList<Mapa_pedido> _mapa_pedidos = new List<Mapa_pedido>();
		public virtual IList<Mapa_pedido> Mapa_pedidos
		{
			get
			{
				return this._mapa_pedidos;
			}
            set
            {
                this._mapa_pedidos = value;
            }
		}
		
		#region ISerializable Implementation
		
		public Mapaentrega()
		{
		}
		
		protected Mapaentrega(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Observacao = info.GetString("Observacao");
			this.Data_entrega = (DateTime?)info.GetValue("Data_entrega", typeof(DateTime?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Observacao", this.Observacao, typeof(string));
			info.AddValue("Data_entrega", this.Data_entrega, typeof(DateTime?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
