#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MaisLifeModel;

namespace MaisLifeModel	
{
	[System.Serializable()]
	public partial class Mapa_pedido : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _mapa;
		public virtual int Mapa
		{
			get
			{
				return this._mapa;
			}
			set
			{
				this._mapa = value;
			}
		}
		
		private int _pedido;
		public virtual int Pedido
		{
			get
			{
				return this._pedido;
			}
			set
			{
				this._pedido = value;
			}
		}
		
		private Pedido _pedido1;
		public virtual Pedido Pedido1
		{
			get
			{
				return this._pedido1;
			}
			set
			{
				this._pedido1 = value;
			}
		}
		
		private Mapaentrega _mapaentrega;
		public virtual Mapaentrega Mapaentrega
		{
			get
			{
				return this._mapaentrega;
			}
			set
			{
				this._mapaentrega = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Mapa_pedido()
		{
		}
		
		protected Mapa_pedido(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Mapa = info.GetInt32("Mapa");
			this.Pedido = info.GetInt32("Pedido");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Mapa", this.Mapa, typeof(int));
			info.AddValue("Pedido", this.Pedido, typeof(int));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
