#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MaisLifeModel;

namespace MaisLifeModel	
{
	[System.Serializable()]
	public partial class Produto_bairro : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _produto;
		public virtual int Produto
		{
			get
			{
				return this._produto;
			}
			set
			{
				this._produto = value;
			}
		}
		
		private int _bairro;
		public virtual int Bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				this._bairro = value;
			}
		}
		
		private decimal _taxa;
		public virtual decimal Taxa
		{
			get
			{
				return this._taxa;
			}
			set
			{
				this._taxa = value;
			}
		}
		
		private Bairro _bairro1;
		public virtual Bairro Bairro1
		{
			get
			{
				return this._bairro1;
			}
			set
			{
				this._bairro1 = value;
			}
		}
		
		private Produto _produto1;
		public virtual Produto Produto1
		{
			get
			{
				return this._produto1;
			}
			set
			{
				this._produto1 = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Produto_bairro()
		{
		}
		
		protected Produto_bairro(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Produto = info.GetInt32("Produto");
			this.Bairro = info.GetInt32("Bairro");
			this.Taxa = info.GetDecimal("Taxa");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Produto", this.Produto, typeof(int));
			info.AddValue("Bairro", this.Bairro, typeof(int));
			info.AddValue("Taxa", this.Taxa, typeof(decimal));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
