#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MaisLifeModel;

namespace MaisLifeModel	
{
	[System.Serializable()]
	public partial class Usuario : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _sobrenome;
		public virtual string Sobrenome
		{
			get
			{
				return this._sobrenome;
			}
			set
			{
				this._sobrenome = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _senha;
		public virtual string Senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				this._senha = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private int? _permissao;
		public virtual int? Permissao
		{
			get
			{
				return this._permissao;
			}
			set
			{
				this._permissao = value;
			}
		}
		
		private IList<Pedido> _pedidos = new List<Pedido>();
		public virtual IList<Pedido> Pedidos
		{
			get
			{
				return this._pedidos;
			}
            set
            {
                this._pedidos = value;
            }
		}
		
		private IList<Endereco> _enderecos = new List<Endereco>();
		public virtual IList<Endereco> Enderecos
		{
			get
			{
				return this._enderecos;
			}
            set
            {
                this._enderecos = value;
            }
		}
		
		private IList<Carrinho> _carrinhos = new List<Carrinho>();
		public virtual IList<Carrinho> Carrinhos
		{
			get
			{
				return this._carrinhos;
			}
            set
            {
                this._carrinhos = value;
            }
		}
		
		#region ISerializable Implementation
		
		public Usuario()
		{
		}
		
		protected Usuario(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Nome = info.GetString("Nome");
			this.Sobrenome = info.GetString("Sobrenome");
			this.Email = info.GetString("Email");
			this.Senha = info.GetString("Senha");
			this.Tipo = info.GetString("Tipo");
			this.Permissao = (int?)info.GetValue("Permissao", typeof(int?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Nome", this.Nome, typeof(string));
			info.AddValue("Sobrenome", this.Sobrenome, typeof(string));
			info.AddValue("Email", this.Email, typeof(string));
			info.AddValue("Senha", this.Senha, typeof(string));
			info.AddValue("Tipo", this.Tipo, typeof(string));
			info.AddValue("Permissao", this.Permissao, typeof(int?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
