//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrinho_produto
    {
        public int id { get; set; }
        public Nullable<int> produto { get; set; }
        public Nullable<int> carrinho { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual carrinho carrinho1 { get; set; }
        public virtual produto produto1 { get; set; }
    }
}
