//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucao_produto
    {
        public int id { get; set; }
        public int devolucao { get; set; }
        public int produto { get; set; }
        public int quantidade { get; set; }
    
        public virtual devolucao devolucao1 { get; set; }
        public virtual produto produto1 { get; set; }
    }
}
