#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

using MaisLifeModel;

namespace MaisLifeModel.Models
{
	[System.Serializable()]
	public partial class Entrada_estoque : System.Runtime.Serialization.ISerializable
	{
		private int _codigo;
		public virtual int Codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				this._codigo = value;
			}
		}
		
		private int _entrada;
		public virtual int Entrada
		{
			get
			{
				return this._entrada;
			}
			set
			{
				this._entrada = value;
			}
		}
		
		private int _estoque;
		public virtual int Estoque
		{
			get
			{
				return this._estoque;
			}
			set
			{
				this._estoque = value;
			}
		}
		
		private DateTime? _data_entrada;
		public virtual DateTime? Data_entrada
		{
			get
			{
				return this._data_entrada;
			}
			set
			{
				this._data_entrada = value;
			}
		}
		
		private Estoque _estoque1;
		public virtual Estoque Estoque1
		{
			get
			{
				return this._estoque1;
			}
			set
			{
				this._estoque1 = value;
			}
		}
		
		private Entrada _entrada1;
		public virtual Entrada Entrada1
		{
			get
			{
				return this._entrada1;
			}
			set
			{
				this._entrada1 = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Entrada_estoque()
		{
		}
		
		protected Entrada_estoque(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Codigo = info.GetInt32("Codigo");
			this.Entrada = info.GetInt32("Entrada");
			this.Estoque = info.GetInt32("Estoque");
			this.Data_entrada = (DateTime?)info.GetValue("Data_entrada", typeof(DateTime?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Codigo", this.Codigo, typeof(int));
			info.AddValue("Entrada", this.Entrada, typeof(int));
			info.AddValue("Estoque", this.Estoque, typeof(int));
			info.AddValue("Data_entrada", this.Data_entrada, typeof(DateTime?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
