//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public entrada()
        {
            this.entrada_estoque = new HashSet<entrada_estoque>();
        }
    
        public int id { get; set; }
        public int numero { get; set; }
        public System.DateTime data { get; set; }
        public int fornecedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrada_estoque> entrada_estoque { get; set; }
        public virtual fornecedor fornecedor1 { get; set; }
    }
}
