#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using MaisLifeModel;

namespace MaisLifeModel.Models
{
	[System.Serializable()]
	public partial class Fornecedor : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _razao_social;
		public virtual string Razao_social
		{
			get
			{
				return this._razao_social;
			}
			set
			{
				this._razao_social = value;
			}
		}
		
		private string _documento;
		public virtual string Documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				this._documento = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _telefone;
		public virtual string Telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				this._telefone = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private IList<Entrada> _entradas = new List<Entrada>();
		public virtual IList<Entrada> Entradas
		{
			get
			{
				return this._entradas;
			}
            set
            {
                this._entradas = value;
            }
		}
		
		#region ISerializable Implementation
		
		public Fornecedor()
		{
		}
		
		protected Fornecedor(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Razao_social = info.GetString("Razao_social");
			this.Documento = info.GetString("Documento");
			this.Nome = info.GetString("Nome");
			this.Telefone = info.GetString("Telefone");
			this.Email = info.GetString("Email");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Razao_social", this.Razao_social, typeof(string));
			info.AddValue("Documento", this.Documento, typeof(string));
			info.AddValue("Nome", this.Nome, typeof(string));
			info.AddValue("Telefone", this.Telefone, typeof(string));
			info.AddValue("Email", this.Email, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
