//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapa_pedido
    {
        public int id { get; set; }
        public int mapa { get; set; }
        public int pedido { get; set; }
    
        public virtual mapaentrega mapaentrega { get; set; }
        public virtual pedido pedido1 { get; set; }
    }
}
