//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaislifeEntities : DbContext
    {
        public MaislifeEntities()
            : base("name=MaislifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bairro> bairro { get; set; }
        public virtual DbSet<carrinho> carrinho { get; set; }
        public virtual DbSet<carrinho_produto> carrinho_produto { get; set; }
        public virtual DbSet<contato> contato { get; set; }
        public virtual DbSet<devolucao> devolucao { get; set; }
        public virtual DbSet<devolucao_produto> devolucao_produto { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<entrada> entrada { get; set; }
        public virtual DbSet<entrada_estoque> entrada_estoque { get; set; }
        public virtual DbSet<estoque> estoque { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<mapa_pedido> mapa_pedido { get; set; }
        public virtual DbSet<mapaentrega> mapaentrega { get; set; }
        public virtual DbSet<parceiro> parceiro { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<produto_bairro> produto_bairro { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_externo> usuario_externo { get; set; }
    }
}
