//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parceiro
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string imagem { get; set; }
        public string enderec { get; set; }
        public string telefone { get; set; }
        public string site { get; set; }
        public string facebook { get; set; }
    }
}
