#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace MaisLifeModel.Models
{
	[System.Serializable()]
	public partial class Parceiro : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _imagem;
		public virtual string Imagem
		{
			get
			{
				return this._imagem;
			}
			set
			{
				this._imagem = value;
			}
		}
		
		private string _enderec;
		public virtual string Enderec
		{
			get
			{
				return this._enderec;
			}
			set
			{
				this._enderec = value;
			}
		}
		
		private string _telefone;
		public virtual string Telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				this._telefone = value;
			}
		}
		
		private string _site;
		public virtual string Site
		{
			get
			{
				return this._site;
			}
			set
			{
				this._site = value;
			}
		}
		
		private string _facebook;
		public virtual string Facebook
		{
			get
			{
				return this._facebook;
			}
			set
			{
				this._facebook = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Parceiro()
		{
		}
		
		protected Parceiro(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Nome = info.GetString("Nome");
			this.Imagem = info.GetString("Imagem");
			this.Enderec = info.GetString("Enderec");
			this.Telefone = info.GetString("Telefone");
			this.Site = info.GetString("Site");
			this.Facebook = info.GetString("Facebook");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Nome", this.Nome, typeof(string));
			info.AddValue("Imagem", this.Imagem, typeof(string));
			info.AddValue("Enderec", this.Enderec, typeof(string));
			info.AddValue("Telefone", this.Telefone, typeof(string));
			info.AddValue("Site", this.Site, typeof(string));
			info.AddValue("Facebook", this.Facebook, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
