//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaisLifeModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto_bairro
    {
        public int id { get; set; }
        public int produto { get; set; }
        public int bairro { get; set; }
        public decimal taxa { get; set; }
    
        public virtual bairro bairro1 { get; set; }
        public virtual produto produto1 { get; set; }
    }
}
