#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace MaisLifeModel	
{
	[System.Serializable()]
	public partial class Contato : System.Runtime.Serialization.ISerializable
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _assunto;
		public virtual string Assunto
		{
			get
			{
				return this._assunto;
			}
			set
			{
				this._assunto = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _telefone;
		public virtual string Telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				this._telefone = value;
			}
		}
		
		private string _mensagem;
		public virtual string Mensagem
		{
			get
			{
				return this._mensagem;
			}
			set
			{
				this._mensagem = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Contato()
		{
		}
		
		protected Contato(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Nome = info.GetString("Nome");
			this.Assunto = info.GetString("Assunto");
			this.Email = info.GetString("Email");
			this.Telefone = info.GetString("Telefone");
			this.Mensagem = info.GetString("Mensagem");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Nome", this.Nome, typeof(string));
			info.AddValue("Assunto", this.Assunto, typeof(string));
			info.AddValue("Email", this.Email, typeof(string));
			info.AddValue("Telefone", this.Telefone, typeof(string));
			info.AddValue("Mensagem", this.Mensagem, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
